name: Code coverage
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  coverage:
    name: Code coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-14 g++-14 gcovr

      - name: Configure CMake for coverage
        run: >
          cmake -B build
          -DCMAKE_CXX_COMPILER=g++-14
          -DCMAKE_C_COMPILER=gcc-14
          -DCMAKE_BUILD_TYPE=Debug
          -DCMAKE_CXX_FLAGS="--coverage -O0 -g"
          -DCMAKE_C_FLAGS="--coverage -O0 -g"
          -DCMAKE_EXE_LINKER_FLAGS="--coverage"
          -S ${{ github.workspace }}

      - name: Build
        run: cmake --build build

      - name: Test
        working-directory: build
        run: ctest --output-on-failure

      - name: Generate coverage report
        run: |
          gcovr --root . ./build \
          --gcov-executable gcov-14 \
          --filter 'include/' \
          --exclude-unreachable-branches \
          --xml-pretty -o coverage.xml

      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: true