name: Code coverage
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  coverage:
    name: Code coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-14 g++-14 gcovr

      - name: Configure CMake for coverage
        run: >
          cmake -B build
          -DCMAKE_CXX_COMPILER=g++-14
          -DCMAKE_C_COMPILER=gcc-14
          -DCMAKE_BUILD_TYPE=Debug
          -DCMAKE_CXX_FLAGS="--coverage -O0 -g"
          -DCMAKE_C_FLAGS="--coverage -O0 -g"
          -DCMAKE_EXE_LINKER_FLAGS="--coverage"
          -S ${{ github.workspace }}

      - name: Build
        run: cmake --build build

      - name: Test
        working-directory: build
        run: ctest --output-on-failure

      - name: Extract coverage percentage
        id: coverage
        run: |
          COVERAGE=$(gcovr -r ${{ github.workspace }} --gcov-executable gcov-14 -e ".*_deps.*" -s | grep "^lines:" | awk '{print $2}' | tr -d '%')
          echo "Coverage is $COVERAGE%"
          echo "percent=$COVERAGE" >> $GITHUB_OUTPUT

      - name: Update gist via cURL
        env:
          GIST_TOKEN: ${{ secrets.GIST_SECRET }}
          GIST_ID: a959a29ceba525fc38f427725e75b15f
          PERCENT: ${{ steps.coverage.outputs.percent }}
        run: |
          if (( $(echo "$PERCENT > 80" | bc -l) )); then COLOR="green";
          elif (( $(echo "$PERCENT > 60" | bc -l) )); then COLOR="yellow";
          else COLOR="red"; fi
          BADGE_JSON=$(jq -nc \
            --arg label "coverage" \
            --arg message "$PERCENT%" \
            --arg color "$COLOR" \
            '{schemaVersion: 1, label: $label, message: $message, color: $color}')
            
            curl -L -X PATCH \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $GIST_TOKEN" \
              -H "X-GitHub-Api-Version: 2026-03-10" \
              https://api.github.com/gists/$GIST_ID \
              -d "$(jq -nc --arg content "$BADGE_JSON" '{"files": {"coverage.json": {"content": $content}}}')"